# src/research_crew/config/tasks.yaml
research_task:
  description: >
   follow these steps :
    1. Analyze the provided topic thoroughly.

    2. condunct the research to gather current insights , trends and expert prespectives on the topic {topic} latest by 2025.

    3. syntheszed the gathered information to identify :
      -core concepts and principles
      -current trends and developments
      -Expert opinions and best practices
      -Real world application and examples
      -potential challenges and solutions

    4. create a comprehensive table of contents that : 
     -Reflects both foundational knowledge and currenet developments.
     -incoporates relevant case studies and examples.
     -Address common question and concerns.
     -include practical apllication  and future developments

    5. structure the content hierarchially , ensuring : 
     -logical flow and progression.
     -clear relationships between sections.
     -Balanced coverage of theoratical and practical aspects.
     -Integration of reserach backed insights.

    6. include various pics related to that particular topic.
     -include image related to the content .
     -if there is any relevant pic available insert it into the report sectional wise.
     - inserting picture should be of valid height and weight. 

    Make sure to organize your findings in a structured format with clear sections.
  expected_output: >
      Please format your response as follows : 
      Topic Analysis
      [Brief overview of the topic and its significant based on the current reserach] 

      key Research insights:
      - [Insight 1 from web research]
      - [Insight 2 from web research]
      - [Insight 3 from web research]

  agent: researcher

analysis_task:
  description: >
    write the title , subtitle , chapters details , the introduction , the conclusions and an image prompt for SEO friendly article
    Please use the topics given by the research agent .
    1. Begin with an executive summary and tell the information regarding which date latest by which date.
    2. Include all key information from the research
    3. Provide insightful analysis of trends and patterns
    4. Offer recommendations or future considerations
    5. Be formatted in a professional, easy-to-read style with clear headings
    6. just fill the content on all sections mentioned in about 100 words and then lastly give a conclusion regarding that topic.

    7. Include citations regarding subtopics in the content. you should give proper citations not mentioning the year.
  expected_output: >
    A polished, professional report on {topic} that presents the research
    findings with added analysis and insights. The report should be well-structured
    with an executive summary, main sections, and conclusion.
  agent: analyst
  context:
    - research_task
  output_file: output/report.md